apiVersion: v1
kind: Service
metadata:
  name: db-movie-service
spec:
  selector:
    app: {{ .Values.db_movie.name }}
  ports:
    - protocol: {{ .Values.db_movie.service.protocol }}
      port: {{ .Values.db_movie.service.port }}
      targetPort: {{ .Values.db_movie.service.targetPort }}
  type: {{ .Values.db_movie.service.type }}