apiVersion: apps/v1
kind: statefulset
metadata:
  name: db-movie-statefulset
spec:
  replicas: {{ .Values.db_movie.replicaCount }}
  selector:
    matchLabels:
      app: db-movie
  template:
    metadata:
      labels:
        app: db-movie
    spec:
      containers:
      - name: db-movie
        image: "{{ .Values.db_movie.image.repository }}:{{ .Values.db_movie.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: db-movie-secret
          - configMapRef:
              name: db-movie-config
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: "db-movie-volume"
        ports:
        - containerPort: 5432
  volumeClaimTemplates:
  - metadata:
      name: "db-movie-volume"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi