apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-cast-statefulset
spec:
  replicas: {{ .Values.db_cast.replicaCount }}
  selector:
    matchLabels:
      app: db-cast
  template:
    metadata:
      labels:
        app: db-cast
    spec:
      containers:
      - name: db-cast
        image: "{{ .Values.db_cast.image.repository }}:{{ .Values.db_cast.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: db-cast-secret
          - configMapRef:
              name: db-cast-config
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-cast-volume
        ports:
        - containerPort: 5432
  volumeClaimTemplates:
  - metadata:
      name: db-cast-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi