apiVersion: v1
kind: Secret
metadata:
  name: db_movie_secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.db_movie.secret.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.db_movie.secret.POSTGRES_PASSWORD }}
